Feature bp 742 replace movai classes with the gd node package
MOV-AI/gd-node pull request #20
Opened 2022-09-08 06:44 UTC by erezz-mov-ai

This branch contains all necessary changed to split movai_classes

- [ ] Make sure you are opening from a **topic/feature/bugfix branch**
- [ ] Ensure that the PR title represents the desired changes
- [ ] Ensure that the PR description detail the desired changes
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

[^note]:
    Put an `x` into the [ ] to show you have filled the information.
    The template comes from https://github.com/MOV-AI/.github/blob/master/.github/pull_request_template.md
    You can override it by creating .github/pull_request_template.md  in your own repository

2022-09-11 11:59 UTC, Mograbi requested changes

2022-09-11 11:59 UTC, Mograbi commented on gd_node/message.py
> +from dal.scopes.message import Message
from dal.scopes import Message

2022-09-11 11:59 UTC, Mograbi commented on gd_node/protocols/movai.py
> +from dal.scopes.robot import Robot
same

2022-09-22 09:16 UTC, erezz-mov-ai commented on gd_node/callback.py
>                          "Layout": Layout,
add another self.global.update if enterprise

2022-09-22 09:17 UTC, erezz-mov-ai commented on gd_node/callback.py
> -                    **{key: getattr(dal.models, key) for key in dal.models.__all__},
add all necessary models, mainly those used by robotics

2022-09-28 09:50 UTC, Mograbi approved these changes

2022-09-28 09:50 UTC, Mograbi approved these changes

2022-09-28 09:51 UTC, merged