Bugfix/bp 841/remove deprecation warnings from container logs
MOV-AI/gd-node pull request #63
Opened 2023-04-13 10:15 UTC by erezz-mov-ai

[BP-841](https://movai.atlassian.net/browse/BP-841)

2023-04-16 15:13 UTC, engdorm approved these changes

2023-04-16 15:15 UTC, engdorm commented
why not use the RUNTIME?
Or the same logger?

2023-04-16 15:23 UTC, engdorm requested changes
you cant remove all logs with ignore
its way to general
we need to update all of the old libs
and fix those warnings the right way

2024-05-22 17:16 UTC, AlexFernandes-MOVAI commented
deprecated

2024-05-22 17:16 UTC, closed without merging